# Conexión a SQL Server (ajusta según tu instancia)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VidaFitDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sql
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate (opcional, pero ayuda a mostrar SQL)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect

# Para que JdbcTemplate funcione bien
spring.sql.init.mode=always