spring.application.name=VidaFit

#==========================
# SQL SERVER
#==========================

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VidaFit_Proyecto;encrypt=false;trustServerCertificate=true

spring.datasource.username=sa

spring.datasource.password=VidaFit123*

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#==========================
# JDBC
#==========================

spring.sql.init.mode=never
spring.session.jdbc.initialize-schema=never
#==========================
# LOG
#==========================

logging.level.org.springframework.jdbc.core=DEBUG

server.port=8080